import "./globals.css"
import { Inter } from "next/font/google"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Risk Visualization App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className + "bg-primary"}>
        <nav className="navbar bg-accent">
          <a className="btn btn-outline normal-case text-xl">Risk-Viz</a>
        </nav>
        <div className="bg-base-100">{children}</div>
      </body>
    </html>
  )
}
