import "./globals.css"
import { Inter } from "next/font/google"
import "leaflet/dist/leaflet.css"
import Script from "next/script"
import Link from "next/link"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Risk Visualization App",
  // description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <html lang="en">
        <head>
          <link
            rel="stylesheet"
            href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css"
            integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI="
            crossOrigin=""
          />
          <Script
            src="https://unpkg.com/leaflet@1.9.3/dist/leaflet.js"
            integrity="sha256-WBkoXOwTeyKclOHuWtc+i2uENFpDZ9YPdf5Hf+D7ewM="
            crossOrigin=""
          ></Script>
        </head>
        <body className={inter.className + "h-screen m-0 p-0 bg-primary"}>
          <nav className="navbar bg-neutral">
            <a className="btn btn-outline normal-case text-xl text-accent">
              Risk-Viz
            </a>
          </nav>
          <div>{children}</div>
          <footer className="footer footer-center p-4 bg-neutral text-neutral-content mt-64">
            <div>
              <Link href="https://haewook-lee.github.io">
                Copyright © 2023 - All right reserved by Haewook Lee
              </Link>
            </div>
          </footer>
        </body>
      </html>
    </>
  )
}
