import "./globals.css"
import { Inter } from "next/font/google"
import "leaflet/dist/leaflet.css"
import Script from "next/script"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Risk Visualization App",
  // description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <html lang="en">
        <head>
          <link
            rel="stylesheet"
            href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css"
            integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI="
            crossOrigin=""
          />
          <Script
            src="https://unpkg.com/leaflet@1.9.3/dist/leaflet.js"
            integrity="sha256-WBkoXOwTeyKclOHuWtc+i2uENFpDZ9YPdf5Hf+D7ewM="
            crossOrigin=""
          ></Script>
        </head>
        <body className={inter.className + "bg-primary"}>
          <nav className="navbar bg-accent">
            <a className="btn btn-outline normal-case text-xl">Risk-Viz</a>
          </nav>
          <div className="bg-base-100">{children}</div>
        </body>
      </html>
    </>
  )
}
